
#+TITLE: Tutorial
#+SUBTITLE: Modal editing


* Introduction
Before we get to actually doing things in Photon, we need to understand the special way in which Photon deals with commands and text input.



* What is modal editing?
In Photon, you can be in one of three modes: *Normal mode*, *Insert mode*, or *Visual mode*. You can see the current mode in the top-left corner of your window: *N* represents normal mode, *I* represents insert mode, and *V* represents visual mode. You can also quickly recognize the mode through the color of the symbol: *Normal* is green, *Insert* is blue, and *Visual* is red. 


** Normal mode
Normal mode is used to *move around files and execute commands*.

When you open a file, it will always be in normal mode by default. In this mode, all of your key presses will be registered as *commands* rather than text input. This mode is often used for moving around your document quickly and manipulating text (e.g., copying/pasting).

*Try it out!*
#+begin_src

First make sure you're in Normal mode; check that in the top left corner, there is a green N. If not, press <ESCAPE> to return to normal mode.

You can move left/down/up/right with the <h>/<j>/<k>/<l> keys. Try pressing these keys now, and see what happens! We'll cover advanced movement in more detail later.

IMPORTANT NOTE: In general, keybinds are CASE-SENSITIVE. Make sure your CAPS LOCK is off to avoid confusion!

#+end_src



** Insert mode
Insert mode is used to *insert text*.

You can easily tell when you are in insert mode, since the cursor shape changes from a square to a line. Note that when this tutorial refers to the "cursor", it is speaking about the blinking "text cursor," not your mouse pointer.

If you are currently in normal mode, pressing ~<i>~ will enter insert mode in front of the current character, and pressing ~<a>~ will enter insert mode with the cursor after the current character. Pressing ~<ESCAPE>~ returns you to Normal mode.

*Try it out!*
#+begin_src

First, ensure you are in Normal mode. Then, using the <j> and <k> keys, move your cursor down to line below, and use <h>/<l> to position the cursor between the arrows.

-->          <--

Press <i> and notice that (1) your cursor changes and (2) key presses on your keyboard now insert text.

When you are done, press <ESCAPE> to return to normal mode; notice that <h> <j> <k> <l> register as movement commands again rather than text input.
#+end_src



** Visual mode
Visual mode is used to *select regions of text*, typically to copy or delete.

If you are currently in normal mode, pressing ~<v>~ will enter visual mode, and pressing ~<SHIFT-v>~ will enter visual-line mode (selecting lines rather than individual characters). Again, pressing ~<ESCAPE>~ returns you to normal mode.

*Try it out!*
#+begin_src

Ensure you are in Normal mode. Move your cursor into the box using <h> <j> <k> <l>.

Press <v> to enter Visual mode, then move the cursor with <h> <j> <k> or <l>. Notice that moving around now selects the region.

Press <ESCAPE> to return to Normal mode. Now press <SHIFT-V>. You are selecting lines now! Try using <j> and <k> to select multiple lines. When you are done, press <ESCAPE> again.

#+end_src




* Advanced motions
Congratulations! You now have a strong understanding of the fundamentals of the three modes. Let's move on to some important advanced commands that will help you navigate quicker and execute common actions.


** Moving around faster
Moving around with just ~<hjkl>~ is slow and tedious. To move quicker, use ~<SHIFT>~ or ~<CTRL>~ in combination with ~<hjkl>~.

Here's a table to recap all of the movement commands so far:

|-----------+----------------------------------------------------------|
| *Keybind*   | Action                                                   |
|-----------+----------------------------------------------------------|
| ~h/l~       | Move forwards/backwards by one *character*                 |
| ~SHIFT-h/l~ | Move forwards/backwards by one *word*                      |
| ~CTRL-h/l~  | Move forwards/backwards to the beginning/end of the *line* |
|-----------+----------------------------------------------------------|
| ~j/k~       | Move up/down *lines*                                       |
| ~SHIFT-j/k~ | Move up/down *paragraphs*                                  |
| ~CTRL-j/k~  | Move up/down to the top/bottom of the *buffer*             |
|-----------+----------------------------------------------------------|

*Try it out!*
#+begin_src

Ensure you are in normal mode. Jump into this box by pressing <SHIFT-j> or <SHIFT-k>. Once you're inside, navigate your cursor onto this line of text. Try using <SHIFT-h> and <SHIFT-l> to move forward/backwards quickly, then try to use <CTRL-h> and <CTRL-l> to jump to the beginning/end of lines.
  
#+end_src


Additionally, all of the previously mentioned motions can be prefixed with a number to repeat it multiple times. For instance, typing ~<4h>~ jumps the cursor back by 4 characters; ~<2j>~ jumps you down two lines; ~<3 SHIFT-j>~ jumps you down three paragraphs, etc.



** Copying and pasting
Copying and pasting in Photon is different from other applications, since the usual ~<CTRL-c>~, ~<CTRL-v>~, and ~<CTRL-x>~ keybinds are not used. Instead, ~<y>~ is used to "yank" (copy) text, ~<p>~ is used to paste text, and ~<x>~ is used to cut text.

*Note*: ~<p>~ (lowercase p) pastes _behind_ the cursor, whereas ~<P>~ (uppercase P) pastes _in front of_ the cursor. This may seem like an insignificant distinction, but being able to use both variants of the paste command gives you much better fine-grained control.

*Try it out!*
#+begin_src

Select part of this line by entering visual mode with <v> and moving left/right with <h>/<l>. Then, press <y> to copy the selected region.
Now, move your cursor between the arrows below, and press <p> to paste!
----->                    <-----

Now, select part of the text below, and use <x> to cut it. Then paste where it says "Paste here" by pressing <p>!
-----> Here is some text. Select some of this line. Try using visual mode to select a region! <-----
-----> Paste here:                                                                            <-----

#+end_src


*Note*: in Photon, you can use ~<backspace>~ in normal mode to delete text *without* copying it to the clipboard.

*Try it out!*
#+begin_src

Move your cursor onto the first bullet point below, and press <SHIFT-V> to enter line-wise visual mode. Note that last bullet is 2 lines below the selected line; thus, you can press <2j> to select all the bullets. Or, press <j> twice.

When you have successfully selected the region, use <backspace> to delete it without cutting it. When you are done, press <ESCAPE> to return to normal mode.

- Here's the first point
- Here's the second point
- Here's the last point

#+end_src



** Undo and redo
It's simple! Press ~<u>~ to undo and ~<r>~ to redo.

*Note*: sometimes it can be unpredictable how far back the undo command goes. If you are thinking of making a change that you may want to undo, you should *save* your file before making the change. When you manually save the file, it creates a point that you can undo back to.

*Try it out!*
#+begin_src

1. Move your cursor onto the line below the instructions. Press <SHIFT-V> then <x> in Normal mode to cut the line.
2. Press <u> to undo the deletion.
3. Press <r> to redo the deletion.

-----> Here is a line of text! <-----

#+end_src


** [Advanced]: registers
/Note: this is relatively advanced and is not crucial knowledge; you can skip it if you like. However, you may find it useful!/

Technically, Photon doesn't have a singular clipboard that it copies to. Instead, it has a large number of "registers." By default, using ~<y>~, ~<x>~, etc. copies to register _0_. However, you can specify a register to use by pressing ~<">   <[register name]>   <[command]>~. I recommend using the keyboard letters ~<a-z>~ as register names (avoid using numbers as names or special characters).

For example, if I wanted to copy some selected text into register _a_, I would type ~<" a y>~: (~<">~ shows that you are about to specify a register, ~<a>~ designating the register name, and ~<y>~ representing the copy action). Here's a demonstration of why this can be useful:

*Try it out!*
#+begin_src

Move your cursor onto the below line. Try using the relative line number in conjunction with <j> or <k>. Remember, you can enter visual (selection) mode with <v> and then use <h>/<l> to expand the selection.

1. Select some of this row, and press <" a y> to copy it to register a.
2. Select some of this row, and press <" b y> to copy it to register b.
3. Ensuring you are in normal mode, move your cursor inside the below arrows and press <" a p> to paste from register a.
----->                    <-----
4. Move your cursor inside the below arrows and press <" b p> to paste from register b.
----->                    <-----
Copying to different registers can sometimes be useful if you are trying to copy/paste multiple different things constantly!

5. In normal mode, type :reg and press enter. Notice how a window pops up showing what is currently saved in each register! Can you see the contents of the a and b registers?
6. Press <q> to close the popup window.

#+end_src



** [Advanced]: find
/Note: this is relatively advanced and is not crucial knowledge; you can skip it if you like. However, you may find it useful!/

Photon has a command that allows you to quickly jump your cursor to any visible text on your screen (even if that text is in a different window! We'll cover windows later). You can execute the find command by pressing ~<f>~. The best way to demonstrate this command is through an example.

*Try it out!*
#+begin_src


Let's try out the find command. We are going to try to jump our cursor to the word below; specifically to fix the misspelling. We want to add an "e" after the "i" in "Science", thus, let's jump to the "i".

-----> Scince <-----

Begin by pressing <f> (to start the command), and <i> (the character we want to jump to). Note that new characters have shown up over the above word (red and blue). Press those keys.

Your cursor should have now jumped to the "i" in "Scince" above. Now, press <a> to enter insert mode with the cursor AFTER the "i". Add an "e", and press <ESC> to return to normal mode.

Note: This may seem pointless for short movements around a document. To navigate around a sentence or paragraph, it is often faster to use <h/j/k/l> and their SHIFT-/CTRL- versions. However, when jumping from the top of your screen to the bottom, or between windows, it can be very fast when you get used to it; indeed, it can be much quicker than using the mouse to move your cursor.

#+end_src

** Conclusion
Congratulations! You now have a pretty good mastery of Photon's basic modal commands. This can be pretty overwhelming at first, but can also massively improve your efficiency in the long run. Remember, the mouse still works - you can always use it to move around and select regions. However, I recommend slowly building up the muscle memory to use keyboard-style movement.

That was a lot, so let's quickly summarize what we learned, and what parts of it were crucial to actually use Photon.



** Summary
Before you move on to more interesting sections, here's a summary:

*[Crucial to know]*:
- *Normal mode* is for commands, *insert mode* is to edit text, *visual mode* is to select regions of text
  - Check your current mode by looking in the top-left corner
- Copy/cut/paste with ~<y>~ ~<x>~ ~<p>~
- Undo/redo with ~<u>~ and ~<r>~

*[Optional]*:
- Moving with ~<h>~ ~<j>~ ~<k>~ ~<l>~ and their ~<SHIFT>/<CTRL>~ versions
- Combining movement commands with numerical prefixes (e.g., ~<3h>~) to move multiple times
- Advanced copying/cutting into registers, and pasting from them with ~< " [register letter] [command] >~
- The "find" command for jumping to a visible character with ~<f>~


|------------|
| [[file:1.2 \[Tutorial\].org][Next >]]     |
|------------|
| [[file:1.0 \[Tutorial\].org][< Previous]] |
|------------|
