    FROM debian:bookworm-slim AS emacs-compiler

    RUN apt-get update

    RUN \
    apt-get install --no-install-recommends -y \
    ca-certificates \
    git \
    build-essential \
    libgccjit-12-dev \
    libjansson-dev \
    autoconf \
    texinfo

    WORKDIR /tmp
    RUN git clone --depth 1 https://git.savannah.gnu.org/git/emacs.git

    # WORKDIR /tmp/emacs
    # RUN \
    # apt-get install --no-install-recommends -y build-essential 

 




#    FROM debian:bookworm-slim
#
#    RUN \
#    apt-get update
#
#    RUN \
#    apt-get install --no-install-recommends -y \
#    gcc \
#    git \
#    curl \
#    npm \
#    fish
#
#    RUN \
#    apt-get install --no-install-recommends -y \
#    python3 \
#    python3-pip \
#    octave
#
#    RUN \
#    apt-get install --no-install-recommends -y \
#    libtree-sitter-dev \
#    aspell \
#    aspell-en
#
#    RUN \
#    npm install -g npm@10.7.0 && npm install -g git+https://gitlab.com/matsievskiysv/math-preview
#
#    RUN \
#    curl --proto '=https' --tlsv1.2 -fsSL	https://drop-sh.fullyjustified.net | sh
#
#    RUN \
#    curl -sS https://starship.rs/install.sh | sh -s -- --yes
#
#    COPY fonts/ /usr/share/fonts/
#    COPY init.el /root/.emacs.d/init.el
#    COPY add-ons /root/.emacs.d/add-ons
#    COPY snippets /root/.emacs.d/snippets-core/
#    COPY .zshrc /root/.zshrc
#    COPY starship.toml /root/.config/starship.toml
#    COPY chromium.conf /etc/chromium/chromium.conf
#
#    ENV CHROME_BIN=/usr/bin/chromium \
#    CHROME_PATH=/usr/lib/chromium/
#
#    ENV DISPLAY=host.docker.internal:0.0
#
#    RUN apt-get install -y --no-install-recommends emacs
#
#    ENTRYPOINT ["emacs"]
