;; -*- lexical-binding: t; -*-

(define-minor-mode photon-mode
  "Minor mode for my personal keybindings."
  :init-value t
  :global t
  :keymap photon-keymap)

(add-to-list 'emulation-mode-map-alists
     	     `((photon-mode . ,photon-keymap)))
(photon-mode t)

(dolist (binding '(
		   ("M-h" . windmove-left)
     		   ("M-j" . windmove-down)
     		   ("M-k" . windmove-up)
     		   ("M-l" . windmove-right)
     		   ;; ("C-j" . photon-C-j)
     		   ;; ("C-k" . photon-C-k)
     		   ("C-/ k" . helpful-key)
     		   ("C-/ f" . helpful-function)
     		   ("C-/ v" . helpful-variable)
		   ("S-<return>" . photon-open-docs)
     		   ("C-<return>" . photon-toggle)
		   ("M-<backspace>" . photon-delete-word)
		   ("C-<backspace>" . photon-delete)
		   ("C-s" . photon-occur)))
  (define-key photon-keymap (kbd (car binding)) (cdr binding)))

(dolist (binding '(("M-u" . goto-pin-u)
                   ("M-i" . goto-pin-i)
                   ("M-o" . goto-pin-o)
                   ("M-p" . goto-pin-p)
                   ("M-U" . set-pin-u)
                   ("M-I" . set-pin-i)
                   ("M-O" . set-pin-o)
                   ("M-P" . set-pin-p)))
  (define-key photon-keymap (kbd (car binding)) (cdr binding)))

(dolist (state '("normal" "visual"))
  (let ((map (symbol-value (intern (concat "evil-" state "-state-map")))))
    (define-key map (kbd "<backspace>") "\"_x")
    ;; (define-key map (kbd "H") 'evil-backward-word-begin)
    ;; (define-key map (kbd "J") 'photon-J)
    ;; (define-key map (kbd "K") 'photon-K)
    ;; (define-key map (kbd "L") 'evil-forward-word-end)
    ;; (define-key map (kbd "C-h") 'evil-first-non-blank)      
    ;; (define-key map (kbd "C-j") 'evil-goto-line)
    ;; (define-key map (kbd "C-k") 'evil-goto-first-line)      
    ;; (define-key map (kbd "C-l") 'evil-last-non-blank)
    (define-key map (kbd "m") 'evil-avy-goto-char)
    (define-key map (kbd "r") 'evil-redo)))

(evil-set-leader '(normal visual motion) (kbd "SPC"))
(evil-set-leader '(normal visual motion) (kbd "C-SPC"))
(with-eval-after-load 'dired
  (define-key dired-mode-map (kbd "<normal-state> SPC") (lookup-key evil-normal-state-map (kbd "SPC"))))
(dolist (binding '(
		   ;; Basic commands
		   ("s" . save-buffer)
		   ("S" . write-file)
		   ("o" . find-file)
		   ("O" . project-find-file)
		   ("f" . consult-line)
		   ("F" . consult-ripgrep)
		   ("x" . execute-extended-command)
		   ("p" . persp-switch)
		   ("b" . persp-switch-to-buffer*)
		   ("B" . project-switch-to-buffer)
		   ("k" . kill-current-buffer)
		   ("l" . next-buffer)
		   ("h" . previous-buffer)
		   ("z" . photon-focus-buffer)
		   ("q" . (lambda () (interactive) (delete-window) (balance-windows)))
		   ("u" . revert-buffer-quick)
		   ;; Programming
		   ("RET e" . photon-eglot)
		   ("RET r" . eglot-rename)
		   ("RET a" . eglot-code-actions)
		   ("RET <tab>" . photon-reindent-buffer)
		   ("RET m" . consult-imenu)
		   ("RET M" . consult-imenu-multi)
		   ("RET f" . consult-flymake)
		   ("RET j" . consult-compile-error)
		   ("RET i" . (lambda () (interactive) (call-interactively 'eglot) (photon-dape) (revert-buffer-quick))) 
		   ("RET d" . photon-dape)
		   ("RET b" . dape-breakpoint-toggle)
		   ("RET c" . dape-breakpoint-expression)
		   ("RET RET" . photon-compile)
		   ("RET v" . photon-venv)
		   ;; Window management
		   ("w r" . (lambda () (interactive) (split-window-right) (balance-windows)))
		   ("w b" . (lambda () (interactive) (split-window-below) (balance-windows)))
		   ("w =" . balance-windows)
		   ("w +" . text-scale-increase)
		   ("w _" . text-scale-decrease)
		   ("w [" . (lambda () (interactive) (global-text-scale-adjust 2) (kbd "<escape>") (princ "")))
		   ("w ]" . (lambda () (interactive) (global-text-scale-adjust -2) (kbd "<escape>") (princ "")))
		   ;; Rust
		   ("r RET" . rustic-cargo-run)
		   ("r r" . rustic-cargo-run)
		   ("r a" . (lambda () (interactive) (funcall 'rustic-cargo-run t)))
		   ("r b" . rustic-cargo-build)
		   ("r t" . rustic-cargo-test)
		   ("r TAB" . rustic-cargo-fmt)
		   ("r c" . rustic-cargo-check)
		   ("r d a" . rustic-cargo-add)
		   ("r d r" . rustic-cargo-rm)
		   ("r d m" . rustic-cargo-add-missing-dependencies)
		   ("r d u" . rustic-cargo-upgrade)
		   ;; ML
		   ("m m" . chatgpt-shell)
		   ("m c" . chatgpt-shell-swap-model)
		   ("m i" . chatgpt-shell-quick-insert)
		   ("m e" . chatgpt-shell-explain-code)
		   ("m f" . chatgpt-shell-fix-error-at-point)
		   ))
  (evil-define-key '(normal visual motion) 'global (kbd (concat "<leader> " (car binding))) (cdr binding)))
