;; -*- lexical-binding: t; -*-

(define-minor-mode photon-mode
  "Minor mode for my personal keybindings."
  :init-value t
  :global t
  :keymap photon-keymap)

(add-to-list 'emulation-mode-map-alists
     	     `((photon-mode . ,photon-keymap)))
(photon-mode t)

(dolist (binding '(
		   ("M-h" . windmove-left)
     		   ("M-j" . windmove-down)
     		   ("M-k" . windmove-up)
     		   ("M-l" . windmove-right)
		   ("M-q" . photon-M-q)
     		   ("C-n" . vertico-next)
     		   ("C-p" . vertico-previous)
		   ("C-u" . evil-scroll-up)
		   ("C-d" . evil-scroll-down)
		   ("C-c" . (lambda () (interactive)
			      (cond
			       ((minibuffer-window-active-p (selected-window)) (keyboard-escape-quit))
			       ((evil-visual-state-p) (evil-exit-visual-state))
			       (t (evil-normal-state)))))
     		   ("C-/ k" . helpful-key)
     		   ("C-/ f" . helpful-function)
     		   ("C-/ v" . helpful-variable)
		   ("M-#" . async-eshell-command)
		   ("S-<return>" . eldoc-box-help-at-point)
     		   ("C-<return>" . photon-toggle)
		   ("M-<backspace>" . photon-delete-word)
		   ("C-<backspace>" . photon-delete)
		   ("C-s" . photon-occur)
		   ("C-r" . query-replace)))
  (define-key photon-keymap (kbd (car binding)) (cdr binding)))

(dolist (state '("normal" "visual"))
  (let ((map (symbol-value (intern (concat "evil-" state "-state-map")))))
    (dolist (binding '(
		       ("<backspace>" . "\"_x")
		       ("r" . evil-redo)
		       ("U" . winner-undo)
		       ("R" . winner-redo)
		       ("g c" . comment-line)))
      (define-key map (kbd (car binding)) (cdr binding)))))

(evil-set-leader '(normal visual motion) (kbd "SPC"))
(evil-set-leader '(normal visual motion) (kbd "C-SPC"))
(with-eval-after-load 'dired
  (define-key dired-mode-map (kbd "<normal-state> SPC") (lookup-key evil-normal-state-map (kbd "SPC"))))

(dolist (binding '(
		   ;; Basic commands
		   ("s" . save-buffer)
		   ("S" . write-file)
		   ("o" . find-file)
		   ("O" . project-find-file)
		   ("C-o" . photon-telescope-open)
		   ("f" . photon-line)
		   ("F" . photon-rg)
		   ("C-f" . photon-telescope-rg)
		   ("p" . persp-switch)
		   ("b" . persp-switch-to-buffer*)
		   ("B" . project-switch-to-buffer)
		   ("k" . kill-current-buffer)
		   ("q" . (lambda () (interactive) (delete-window) (balance-windows)))
		   ("l" . next-buffer)
		   ("h" . previous-buffer)
		   ("z" . photon-focus-toggle)
		   ("u" . revert-buffer-quick)
		   ("#" . scratch-buffer)
		   ;; Programming
		   ("RET e" . photon-eglot)
		   ("RET r" . eglot-rename)
		   ("RET a" . eglot-code-actions)
		   ("RET s" . consult-eglot-symbols)
		   ("RET q" . devdocs-lookup)
		   ("RET <tab>" . photon-reindent-buffer)
		   ("RET m" . consult-imenu)
		   ("RET M" . consult-imenu-multi)
		   ("RET f" . consult-flymake)
		   ("RET j" . consult-compile-error)
		   ("RET i" . (lambda () (interactive) (call-interactively 'eglot) (photon-dape) (revert-buffer-quick))) 
		   ("RET d" . photon-dape)
		   ("RET b" . dape-breakpoint-toggle)
		   ("RET c" . dape-breakpoint-expression)
		   ("RET RET" . photon-compile)
		   ("RET v" . photon-venv)
		   ;; Window management
		   ("w l" . (lambda () (interactive) (split-window-right) (balance-windows)))
		   ("w j" . (lambda () (interactive) (split-window-below) (balance-windows)))
		   ("w =" . balance-windows)
		   ("w +" . text-scale-increase)
		   ("w _" . text-scale-decrease)
		   ("w [" . (lambda () (interactive) (global-text-scale-adjust 2) (kbd "<escape>") (princ "")))
		   ("w ]" . (lambda () (interactive) (global-text-scale-adjust -2) (kbd "<escape>") (princ "")))
		   ;; Rust
		   ("r RET" . rustic-cargo-run)
		   ("r r" . rustic-cargo-run)
		   ("r a" . (lambda () (interactive) (funcall 'rustic-cargo-run t)))
		   ("r b" . rustic-cargo-build)
		   ("r t" . rustic-cargo-test)
		   ("r TAB" . rustic-cargo-fmt)
		   ("r c" . rustic-cargo-check)
		   ("r d a" . rustic-cargo-add)
		   ("r d r" . rustic-cargo-rm)
		   ("r d m" . rustic-cargo-add-missing-dependencies)
		   ("r d u" . rustic-cargo-upgrade)
		   ))
  (evil-define-key '(normal visual motion) 'global (kbd (concat "<leader> " (car binding))) (cdr binding)))
